Repository bank-vaults/bank-vaults.dev, pull requests merged in 2024-02, with the labels that each got.

#210 ci: update dependabot config
  .github/dependabot.yaml
Labels: size/XS

#208 docs: Adds styleguide and writing tips
  styleguide.md
Labels: size/M

#213 docs: Temporary changes to blog links
  .github/workflows/ci.yaml
  content/docs/blog/index.md
Labels: size/XS

#202 docs: add everything Azure guide
  content/docs/tips-and-tricks/azure-guide.md
Labels: kind/documentation, area/storage, size/M, area/provider/azure, area/auth

#214 feat: Cancel previous workflow on push
  .github/workflows/ci.yaml
Labels: size/XS
